language: node_js
sudo: false

matrix:
  SENECA_VER=@1.2.0
  SENECA_VER=@1.4.0
  SENECA_VER=@2.0.x

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - npm install seneca$SENECA_VER
  - psql -U postgres -f docker/dbschema.sql
